version: '3.8'

services:
  restaurant-system:
    build: .
    ports:
      - "80:80"
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend/restaurant.db:/app/backend/restaurant.db
    restart: unless-stopped

  # 開發環境服務
  dev-backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - /app/node_modules
    profiles:
      - dev

  dev-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend:/app
      - /app/node_modules
    profiles:
      - dev

  dev-admin:
    build:
      context: ./admin-frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./admin-frontend:/app
      - /app/node_modules
    profiles:
      - dev 